### ISSUE TITLE
Remove VeleroBackup controller and replace it with watch

### ISSUE THREAD

**Issue by mpryc** [migtools/oadp-non-admin#11]
Having two controllers for one Kubernetes object leads to complexity, concurrency issues, and inefficient resource usage. Consolidating logic into a single controller and implementing watch functionality within it is a better approach.

Multiple controllers operating on the same object can introduce race conditions and concurrency issues. If both controllers try to update the object simultaneously, it can lead to inconsistent states or conflicts. We already have controller for VeleroBackup object.

This Issue is to remove VeleroBackup controller and include it's current Reconcile loop functionality within the NonAdminBackup controller.

**Comment by mateusoliveira43** [comment]
commit that introduced it as reference https://github.com/migtools/oadp-non-admin/commit/5ff6f33855b8d8876dff48579fbb6f02cda23f7e

**Comment by shubham-pampattiwar** [comment]
@mpryc Thanks for summing up our discussion. Adding some helpful links with regards to the issue fix:
Controller API watches: https://github.com/openshift/oadp-operator/blob/76f0049ebe2dd3cb4e5ed710553d76323a8f236b/controllers/dpa_controller.go#L149 
Predicate logic to filter out events based on labels: https://github.com/openshift/oadp-operator/blob/76f0049ebe2dd3cb4e5ed710553d76323a8f236b/controllers/predicate.go#L12 
Responsibilities of the Velero Backup controller that can be added as a task in Non-Admin Backup controller reconcile logic and thus removing Velero Backup controller altogether: https://github.com/migtools/oadp-non-admin/blob/065eed67867eecd4422b89fe6808172ca05c4316/internal/controller/velerobackup_controller.go#L53-L92

**Comment by mpryc** [comment]
> commit that introduced it as reference [5ff6f33](https://github.com/migtools/oadp-non-admin/commit/5ff6f33855b8d8876dff48579fbb6f02cda23f7e)

@mateusoliveira43 thanks for this. The RBAC imo will need to stay as we will need to update the VeleroBackup from NonAdminBackup controller. So this can't be removed: https://github.com/migtools/oadp-non-admin/commit/5ff6f33855b8d8876dff48579fbb6f02cda23f7e#diff-6d4c4e29ec096149781536bb9118fde8242c1901df764e3eda3019ac8503d6c7
