### ISSUE TITLE
Control over general Velero Backup/Restore Spec that gets exposed or allow listed via NAB/NAR CRD spec.

### ISSUE THREAD

**Issue by shubham-pampattiwar** [migtools/oadp-non-admin#37]
The Velero Backup CR/Restore CR  consists of a plethora of Backup/Restore Spec options. It might be desirable to have a control over the spec that is exposed or may be allowlisted for non-admin users.
- For instance, Backup Spec `IncludedNamespaces` should by default be the non-admin user's namespace as this is a scoped backup operation
- Another instance is mentioned in the [relevant discussion](https://github.com/migtools/oadp-non-admin/discussions/33) of cluster admins wanting to set a default backup TTL for all the non-admin users
- Or maybe the cluster-admins want to enforce that only fs-backups should be used for volumes, so `defaultVolumesToFSBackup` should be true for all non-admin backups

**Comment by shubham-pampattiwar** [comment]
Might need some design, current approach of accepting values from cm is added in main deisgn

**Comment by mateusoliveira43** [comment]
As mentioned in https://github.com/migtools/oadp-non-admin/issues/35, this also needs to apply to Restore specs

@shubham-pampattiwar can you please update issue title to reflect this (or better to have one issue per object?)

**Comment by shubham-pampattiwar** [comment]
@mateusoliveira43 Done, updated
