### ISSUE TITLE
NonAdminBackupReconciler structure should not have references to context etc...

### ISSUE THREAD

**Issue by mpryc** [migtools/oadp-non-admin#52]
Current implementation uses references to the Context and other parts. This should be removed, because in case we have more then one worker that reconciles we will have race condition on setting those references:

```
// NonAdminBackupReconciler reconciles a NonAdminBackup object
type NonAdminBackupReconciler struct {
	client.Client
	Scheme         *runtime.Scheme
	Log            logr.Logger
	Context        context.Context
	NamespacedName types.NamespacedName
}
```

This is change that will require quite a bit of refactoring code, because currently other functions are using the embedded to that structure references.

**Comment by mateusoliveira43** [comment]
@mpryc this is in ready for review in our board. What is the related work?

**Comment by mpryc** [comment]
I think we can close this as it was resolved with:

https://github.com/migtools/oadp-non-admin/pull/54

**Comment by mpryc** [comment]
One note. We have and will continue the need to have the reference to context in the structure, however as in the #54 we removed re-assignment of this context within Reconcile loop:

```
r.Context = ctx
```
