### ISSUE TITLE
Update NAB object status appropriately if VeleroBackup already exists for the NAB object 

### ISSUE THREAD

**Issue by shubham-pampattiwar** [migtools/oadp-non-admin#59]

**Comment by mateusoliveira43** [comment]
Are we able to reproduce this error constantly :question: I think we talked about this being a corner case

If it is a corner case, would not prioritize it now

**Comment by mpryc** [comment]
Agree this is corner case as we generate names based on the NAB name, namespace and hash, so it's really corner case to expect VeleroBackup to be there beforehand.

**Comment by shubham-pampattiwar** [comment]
Right now I get the following status on NAB object if the VeleroBackup object already exists:

**Comment by mateusoliveira43** [comment]
@shubham-pampattiwar now I am confused

is not the bug you are worried, but only a feedback message that NAB created Velero Backup :question:

**Comment by shubham-pampattiwar** [comment]
We want to keep NAB : VeleroBackup :: 1:1

**Comment by shubham-pampattiwar** [comment]
I will try to reproduce this and comment again

**Comment by mateusoliveira43** [comment]
@shubham-pampattiwar can you test this in https://github.com/migtools/oadp-non-admin/pull/73 ?

I think the error was related to the race condition I fixed there

On your example https://github.com/migtools/oadp-non-admin/issues/59#issuecomment-2096833461

it failed here
https://github.com/migtools/oadp-non-admin/blob/4b2f57f3ad905456240e230895148a6d8f2a4be1/internal/controller/nonadminbackup_controller.go#L306-L315

and on the next reconcile it went here
https://github.com/migtools/oadp-non-admin/blob/4b2f57f3ad905456240e230895148a6d8f2a4be1/internal/controller/nonadminbackup_controller.go#L265
