### ISSUE TITLE
Create `arm64` images in PROW images job

### ISSUE THREAD

**Issue by mateusoliveira43** [migtools/oadp-non-admin#74]
We need to add `arm64` images to PROW images job

We need changes in Dockerfile of the repo and in PROW repo

Changes in this repo:
- Dockerfile 
  ```diff
  -FROM golang:1.22 AS builder
  +FROM --platform=$BUILDPLATFORM golang:1.22 AS builder
  +ARG BUILDPLATFORM
  ```
- probably some logic in Makefile to choose platform

Changes in PROW repo:
- add `.config.prowgen` like https://github.com/openshift/release/blob/master/ci-operator/config/openshift/oadp-operator/.config.prowgen to https://github.com/openshift/release/tree/master/ci-operator/config/migtools/oadp-non-admin
- add `multi_arch: true` here https://github.com/openshift/release/blob/master/ci-operator/config/migtools/oadp-non-admin/migtools-oadp-non-admin-master.yaml#L8

**Comment by shubham-pampattiwar** [comment]
I have 2 PRs up for this issue:
- https://github.com/migtools/oadp-non-admin/pull/75 
- https://github.com/openshift/release/pull/56106
