### ISSUE TITLE
CI should check if Velero version is the same as used by OADP

### ISSUE THREAD

**Issue by mateusoliveira43** [migtools/oadp-non-admin#76]
CI should periodically check if the Velero version NAC uses
https://github.com/migtools/oadp-non-admin/blob/4b2f57f3ad905456240e230895148a6d8f2a4be1/go.mod#L79
is in sync with the one OADP uses (for each compatible branch)

This check should be added here
https://github.com/migtools/oadp-non-admin/blob/4b2f57f3ad905456240e230895148a6d8f2a4be1/.github/workflows/ci.yml#L66-L89

Already started discussion https://github.com/migtools/oadp-non-admin/pull/73#discussion_r1743695617

**Comment by mateusoliveira43** [comment]
The CI job should also check if CRDs yamls in `hack/extra-crds/` folder (added in https://github.com/migtools/oadp-non-admin/pull/73) are in sync with the Velero version

**Comment by kaovilai** [comment]
CI could open its own PR.. calling go get oadp-operator@branch && go mod tidy.
