### ISSUE TITLE
Use Kubernetes validation instead of writing logic

### ISSUE THREAD

**Issue by mateusoliveira43** [migtools/oadp-non-admin#80]
We currently check for nil NAB backupSpec in code
https://github.com/migtools/oadp-non-admin/blob/4b2f57f3ad905456240e230895148a6d8f2a4be1/internal/common/function/function.go#L96-L98

instead of using Kubernetes API validation. To achieve this, we just need to remove `omitempty` here
https://github.com/migtools/oadp-non-admin/blob/4b2f57f3ad905456240e230895148a6d8f2a4be1/api/v1alpha1/nonadminbackup_types.go#L40

**Comment by kaovilai** [comment]
If omitempty is removed, it means we never really want this to ever be empty.. what's the point of it being a pointer?
