### ISSUE TITLE
Reject NAB CR creation calls for orphaned Velero Backup objects

### ISSUE THREAD

**Issue by shubham-pampattiwar** [migtools/oadp-non-admin#84]
Scenario:
- User creates NAB CR
- Velero Backup gets created 
- User deletes NAB CR (via OC CLI)
- Velero Backup remains orphaned in cluster without any NAB CR mapping
- Now user creates another NAB CR with the same name (In the window of time where NAB-sync-controller does not get the chance to create the NAB CR in-cluster which was deleted by user)
- The user created NAB CR should be blocked from creation

Solution approach:
- Implement a Validating Admission Web-hook to reject the NAB create call from user using the data by setting the informer on Velero Backup objects.

**Comment by mpryc** [comment]
Would it make sense to add the validation webhook in OADP rather than non admin part ? This could allow such webhook to reject NAB objects when NAB controller is not installed in the cluster (something @shawn-hurley requested in the past).

**Comment by mateusoliveira43** [comment]
Issue origin https://github.com/migtools/oadp-non-admin/pull/73#pullrequestreview-2322124621

We are still waiting to check how Velero handles this case to apply the same solution, right?

**Comment by mpryc** [comment]
My opinion is that we don't have to have the `NonAdminBackup <-> Backup` interaction to be exactly same as Velero Backup. The NonAdminBackup is user facing interface which we provide, so we should make it in a way it won't surprise users.

**Comment by mateusoliveira43** [comment]
Do not forget about [sync controller](https://github.com/migtools/oadp-non-admin/issues/38) when implementing this

Discussion https://redhat-internal.slack.com/archives/C064QSN2YR3/p1728312889734609

**Comment by shubham-pampattiwar** [comment]
Summarizing the slack discussion thread:
In the scenario described in the issue if the actor/user is NAB sync controller then in that case we want the NAB create request to bypass the Validating Admission Webhook. So in order to that we need a way to identify wether the create NAB object request is from the user or the NAB sync controller. The proposed solution here is that we rely on 2 things:
- [One is the managed by label ](https://github.com/migtools/oadp-non-admin/blob/0d30f215b487eb522cf51ecc9e9d478e77c5c602/internal/common/constant/constant.go#L28)
- Second is via checking the [userInfo in admission review](https://github.com/kubernetes/api/blob/f2b3dfac9f9ae72c30f767ec29ff086b0fd10211/admission/v1beta1/types.go#L100) request, webhook should only be bypassed if the request is coming from the NAC controller service account.

**Comment by mateusoliveira43** [comment]
Is this issue still valid?

In the past, creating nab called "test", the related velero backup would always have the same name "test-123456" (as discussed here https://github.com/migtools/oadp-non-admin/issues/90)

Now, each related velero backup has a different name (containing UUID)

To avoid this we would need to check UUID is really unique before applying to nonAdmin object here, right?

https://github.com/migtools/oadp-non-admin/blob/2113181193f1b549482ce1d5a5b985b52e94d2d2/internal/controller/nonadminbackup_controller.go#L544 
This is also tracked here https://github.com/migtools/oadp-non-admin/issues/102

**Comment by mpryc** [comment]
I think we can close this.

Currently there is a major rework of the deletion of NAB implemented that does not require admission webhook.

The  diagram presenting how the three paths of deletion of NAB object works:

https://github.com/migtools/oadp-non-admin/blob/master/docs/design/nab_and_nar_status_update.md#status-update-scenarios

With that the only way to leave orphaned Velero Backup would be to remove finalizer from the NAB and call the `oc delete` on a NAB object.

With standard three deletion methods via spec fields the Velero Backup will get cleanly deleted either by NAC controller (force deletion - leaving s3 storage) or by Velero deletion request (deletion spec, causing s3 storage to be cleaned up).

With `oc delete <NAB>` the NAB will have condition informing that this will not remove Velero Backup and the user should use spec field instead.
