### ISSUE TITLE
`GenerateVeleroBackupName` result is not unique

### ISSUE THREAD

**Issue by mateusoliveira43** [migtools/oadp-non-admin#90]
Given different inputs, `GenerateVeleroBackupName` can return the same result. 
https://github.com/migtools/oadp-non-admin/blob/282620c4f6055e696d5d81df1af124bfd5481b6c/internal/common/function/function.go#L111

This can result in bad user experience, as users can end using other users backup (or when UUID solution is implemented, https://github.com/migtools/oadp-non-admin/issues/89, prevent users from using NonAdminBackup with certain names)

From what I studied, given 2 namespaces that have long names (more than 239 chars), if their names differ only in position 240 or above, any NonAdminBackup that have the same same in these namespaces, the associated VeleroBackup name will be the same.

Example

this
> namespace: mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm1
> NonAdminBackup: example

and this input
> namespace: mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm2
> NonAdminBackup: example

return the same result

## Further investigation

Need to confirm no other scenarios will generate equal names.

**Comment by kaovilai** [comment]
might help to look at https://github.com/kubernetes/enhancements/blob/61b21e5105e5fda4d6c53821ff82dd39a1a98f07/keps/sig-api-machinery/4420-retry-generate-name/README.md

**Comment by mpryc** [comment]
We could drop all together the human readable name of the object and simply use our generated UUID as the Backup object name with retry generate similar to what @kaovilai proposed above. @mateusoliveira43 what do you think? We could also add suffix (not the prefix) to that uuid with namespace and stripped backup name, this way if it's longer then 240 characters, only part of name or namespace will be lost ensuring uniqueness of the name.

**Comment by mateusoliveira43** [comment]
Yeah, a retry on velero backup name seems a good approach

We can discuss the ideas on next meeting

**Comment by mpryc** [comment]
I think this is handled by https://github.com/migtools/oadp-non-admin/pull/101

Also I think we do not need to retry on velero backup name as we generate with UUID as suffix, so there is really minimum chance of collision of that suffix 1 in 2.71 x 10^18 . On top of that we are adding namespace and name of the original NAB object (stripped one), so we lower already minimal chance of such collision.
